import { TimeBlock } from './block.interface';

/**
 * Weekly Schedule Interface
 * 
 * Represents a complete weekly schedule for a user, containing multiple time blocks.
 * Maps to database table: weekly_schedules
 */
export interface WeeklySchedule {
  /** Unique identifier for the weekly schedule */
  scheduleId: string;
  
  /** Reference to the user who owns this schedule */
  userId: string;
  
  /** Start date of the week (Monday in YYYY-MM-DD format) */
  weekStartDate: Date;
  
  /** Flag indicating if this schedule was generated by AI */
  isAiGenerated: boolean;
  
  /** Additional metadata stored as JSON (e.g., generation strategy, AI model used) */
  metadata: Record<string, any>;
  
  /** Array of time blocks within this schedule (optional for lazy loading) */
  timeBlocks?: TimeBlock[];
  
  /** Timestamp when the schedule was created */
  createdAt: Date;
  
  /** Timestamp when the schedule was last updated */
  updatedAt: Date;
  
  /** Soft delete timestamp (null if not deleted) */
  deletedAt?: Date;
}
