import { ApiProperty } from '@nestjs/swagger';
import { TimeBlockDto } from './time-block.dto';

/**
 * Weekly Schedule DTO
 * 
 * Complete representation of a weekly schedule with all time blocks.
 * Used as the main response for GET /v1/weekly-schedules/:scheduleId
 */
export class WeeklyScheduleDto {
  @ApiProperty({
    description: 'Unique identifier for the weekly schedule',
    format: 'uuid',
    example: '550e8400-e29b-41d4-a716-446655440000',
  })
  scheduleId: string;

  @ApiProperty({
    description: 'Reference to the user who owns this schedule',
    format: 'uuid',
    example: '7c9e6679-7425-40de-944b-e07fc1f90ae7',
  })
  userId: string;

  @ApiProperty({
    description: 'Start date of the week (Monday in YYYY-MM-DD format)',
    format: 'date',
    example: '2026-01-13',
  })
  weekStartDate: string;

  @ApiProperty({
    description: 'Flag indicating if this schedule was generated by AI',
    example: true,
  })
  isAiGenerated: boolean;

  @ApiProperty({
    description: 'Additional metadata stored as JSON (e.g., generation strategy, AI model)',
    example: { generationStrategy: 'balanced', aiModel: 'gpt-4o' },
  })
  metadata: Record<string, any>;

  @ApiProperty({
    description: 'Array of time blocks within this schedule',
    type: [TimeBlockDto],
    isArray: true,
  })
  timeBlocks: TimeBlockDto[];

  @ApiProperty({
    description: 'Timestamp when the schedule was created',
    example: '2026-01-09T12:00:00Z',
  })
  createdAt: string;

  @ApiProperty({
    description: 'Timestamp when the schedule was last updated',
    example: '2026-01-09T12:00:00Z',
  })
  updatedAt: string;
}
